CREATE TABLE BACKSAN(
	bnum number(3),
	bname varchar(30),
	bdate date
);

INSERT INTO BACKSAN(BNUM,BNAME,BDATE) VALUES(1,'김백산',TO_DATE('1993/04/21','YYYY/MM/DD'));
INSERT INTO BACKSAN(BNUM,BNAME,BDATE) VALUES(2,'소백산',TO_DATE('1987/08/11','YYYY/MM/DD'));

SELECT * FROM BACKSAN ORDER BY BNUM ASC ;
DELETE FROM BACKSAN WHERE BNAME = '태백산';

DROP TABLE USERINFO;
--실습에 사용 할 테이블
CREATE TABLE USERINFO(
	UINUM NUMBER(10) PRIMARY KEY,
	UIDATE DATE,
	UINAME VARCHAR(30),
	UIADDRESS VARCHAR(300),
	UINICKNAME VARCHAR(30) 
);

CREATE SEQUENCE USERNUMBER
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	MAXVALUE 99999
	NOCYCLE
	NOCACHE;
-- 샘플 테이블에 데이터 삽입 : 3개
INSERT INTO USERINFO(UINUM,UIDATE,UINAME,UIADDRESS,UINICKNAME) VALUES(USERNUMBER.NEXTVAL,TO_DATE('1993/04/21','YYYY/MM/DD'),'전재민','남양주시 퇴계원읍','김백산');
INSERT INTO USERINFO(UINUM,UIDATE,UINAME,UIADDRESS,UINICKNAME) VALUES(USERNUMBER.NEXTVAL,TO_DATE('1980/01/28','YYYY/MM/DD'),'이하늘','남양주시 퇴계원읍','안산주먹');
INSERT INTO USERINFO(UINUM,UIDATE,UINAME,UIADDRESS,UINICKNAME) VALUES(USERNUMBER.NEXTVAL,TO_DATE('1952/08/11','YYYY/MM/DD'),'이병건','남양주시 퇴계원읍','침착맨');

-- 샘플 데이터의 전체 조회
SELECT * FROM USERINFO ;

-- 샘플 데이터에서 기본키를 가지고 1개만 조회하기
SELECT *
FROM USERINFO 
WHERE USNUM = 2;

-- 샘플데이터의 테이터의 기본키를 가지고 조회해서 수정하기
UPDATE USERINFO 
SET USADDRESS = '서울시 서대문구'
WHERE USNUM = 3;

-- 샘플 데이터의 데이터를 기본키로 삭제하기
-- UINUM이 4번인 데이터를 삭제
DELETE FROM USERINFO 
WHERE USNUM = 4;

-- 작업을 완료하고 원본 데이터베이스에 반영
COMMIT;
